# Generated by Django 5.2.4 on 2025-07-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_pro', to='airbnb.country'),
        ),
        migrations.AlterField(
            model_name='propertiesimages',
            name='properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='airbnb.properties'),
        ),
    ]
