# Generated by Django 5.2.4 on 2025-07-16 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0003_alter_properties_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_en',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_ru',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='city_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='city_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='properties_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='properties_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='properties_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='properties_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_booking', to='airbnb.properties'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritesitem',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_item', to='airbnb.favorites'),
        ),
        migrations.AlterField(
            model_name='favoritesitem',
            name='properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_properties', to='airbnb.properties'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='airbnb.country'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='airbnb.properties'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
